name: Test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      CARGO_TERM_COLOR: always
      REDIS_URL: redis://localhost:6379
      RUST_LOG: trace

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Test
        run: cargo nextest run --all-features --no-fail-fast

      - name: Lint
        run: cargo clippy --all-features

      - name: Benchmark
        run: cargo bench
