name: Test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      REDIS_URL: redis://localhost:6379
      RUST_LOG: trace

    steps:

    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test  -- --nocapture
